// Auto-generated by gp_factor_mining.py (Phase 2: Genetic Programming)
// These factors were discovered via evolutionary search and validated
// through multiple lifecycle checks.

pub const GP_FACTOR_NAMES: &[&str] = &[
    "gp_log_678fa802",
];

pub const NUM_GP_FACTORS: usize = 1;

/*
GP-discovered factor expressions:

  gp_log_678fa802: IC=-0.5959
    expr = ((close - log(open)) + sqrt(ts_max(ts_max(ts_min(open, 3), 3), 3)))

Implementation guide:
  Each expression uses: close, open, high, low, volume, returns, vwap, tr
  Operators: +, -, *, / (protected), log, sqrt, abs, sign, inv, neg
  Rolling: ts_mean(x,w), ts_std(x,w), ts_max(x,w), ts_min(x,w), delta(x,d), delay(x,d)
*/