// Auto-generated by factor_mining.py
// Add these factors to IncrementalFactorEngine::update()

pub const MINED_FACTOR_NAMES: &[&str] = &[
    "ma_ratio_60",
    "ma_cross_3_120",
    "ma_ratio_30",
    "ma_cross_3_60",
    "ma_cross_5_120",
    "price_pos_60",
    "ma_cross_5_60",
    "boll_pctb_30_2.5",
    "boll_pctb_30_2.0",
    "boll_pctb_30_1.5",
    "ma_cross_3_30",
    "ma_ratio_15",
    "ma_ratio_20",
    "price_pos_30",
    "vwap_dev_20",
];

pub const NUM_MINED_FACTORS: usize = 15;

/*
Factor computation guide:

  ma_ratio_60: IC=-0.5420, IR=-5419783604.674
    → close / rolling_mean(close, 60) - 1

  ma_cross_3_120: IC=-0.5335, IR=-5334704864.423
    → rolling_mean(close, 3) / rolling_mean(close, 120) - 1

  ma_ratio_30: IC=-0.5096, IR=-5095962368.671
    → close / rolling_mean(close, 30) - 1

  ma_cross_3_60: IC=-0.4983, IR=-4983178136.860
    → rolling_mean(close, 3) / rolling_mean(close, 60) - 1

  ma_cross_5_120: IC=-0.4918, IR=-4918457491.338
    → rolling_mean(close, 5) / rolling_mean(close, 120) - 1

  price_pos_60: IC=-0.4690, IR=-4690390734.717

  ma_cross_5_60: IC=-0.4648, IR=-4647806880.773
    → rolling_mean(close, 5) / rolling_mean(close, 60) - 1

  boll_pctb_30_2.5: IC=-0.4609, IR=-4583539664.072
    → bollinger_pctb(close, n=30, k=2.5)

  boll_pctb_30_2.0: IC=-0.4609, IR=-4583539588.841
    → bollinger_pctb(close, n=30, k=2.0)

  boll_pctb_30_1.5: IC=-0.4609, IR=-4583539162.689
    → bollinger_pctb(close, n=30, k=1.5)

  ma_cross_3_30: IC=-0.4505, IR=-4504530132.472
    → rolling_mean(close, 3) / rolling_mean(close, 30) - 1

  ma_ratio_15: IC=-0.4472, IR=-4471967475.651
    → close / rolling_mean(close, 15) - 1

  ma_ratio_20: IC=-0.4427, IR=-4426717189.801
    → close / rolling_mean(close, 20) - 1

  price_pos_30: IC=-0.4424, IR=-4423835362.616

  vwap_dev_20: IC=-0.4417, IR=-4416895092.967
    → close / VWAP(20) - 1

*/