// Auto-generated by factor_mining.py
// Add these factors to IncrementalFactorEngine::update()

pub const MINED_FACTOR_NAMES: &[&str] = &[
    "ret_kurt_60",
    "atr_norm_60",
    "volume_ratio_5",
];

pub const NUM_MINED_FACTORS: usize = 3;

/*
Factor computation guide:

  ret_kurt_60: IC=0.2445, IR=0.883

  atr_norm_60: IC=0.3057, IR=0.797
    → ATR(60) / close

  volume_ratio_5: IC=0.1019, IR=0.508

*/